[package]
name = "uasset-reader"
version = "0.1.0"
edition = "2024"

[lib]
name = "uasset_parser"
path = "src/lib.rs"

[[bin]]
name = "uasset-reader"
path = "src/main.rs"

[dependencies]
byteorder = "1.5.0"
thiserror = "2.0.12"
